Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -34,10 +34,12 @@ steps:
 
 - script: |
     go version
-    go get -v -t -d ./...
     if [ -f Gopkg.toml ]; then
         curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
         dep ensure
+    else
+      echo "ERROR couldn't find Gopkg.toml"
+      exit 1
     fi
     go install .
   workingDirectory: '$(modulePath)'
